---
apiVersion: v1
kind: List
items:
  - apiVersion: install.tetrate.io/v1alpha1
    kind: Gateway
    metadata:
      name: coffeeshop-ugw
      namespace: caffeine
    spec:
      type: UNIFIED
      #eastWestOnly: true
      kubeSpec:
        service:
          type: LoadBalancer
          #annotations:
          #  external-dns.alpha.kubernetes.io/hostname: gateway.tetrate.io
