---
apiVersion: v1
kind: List
items:
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Gateway
    metadata:
      name: bookinfo-ugw
      annotations:
        tsb.tetrate.io/organization: capitalone
        tsb.tetrate.io/tenant: bookinfo-sidecar
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-gg
    spec:
      workloadSelector:
        namespace: bookinfo
        labels:
          app: bookinfo-ugw
      http:
        - name: bookinfo-ssl
          port: 443
          hostname: "bookinfo.tetrate.io"
          tls:
            mode: SIMPLE
            secretName: bookinfo-cert
            minProtocolVersion: "TLSV1_3"
            maxProtocolVersion: "TLSV1_3"
            cipherSuites: [ "TLS_AES_128_CCM_SHA256"]
            #subjectAltNames: 
            #- bookinfo.tetrate.io
          routing:
            rules:
              - route:
                  serviceDestination:
                    host: "bookinfo/productpage.bookinfo.svc.cluster.local"
                    port: 9080