---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: bookinfo-sidecar
      annotations:
        tsb.tetrate.io/organization: capitalone
    spec:
      description: bookinfo sidecar Mode
      displayName: bookinfo-sidecar
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: bookinfo-ws
      annotations:
        tsb.tetrate.io/organization: capitalone
        tsb.tetrate.io/tenant: bookinfo-sidecar
      labels:
        app: bookinfo
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-gg
      annotations:
        tsb.tetrate.io/organization: capitalone
        tsb.tetrate.io/tenant: bookinfo-sidecar
        tsb.tetrate.io/workspace: bookinfo-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo"
      configMode: BRIDGED
  - apiVersion: tsb.tetrate.io/v2
    kind: WorkspaceSetting
    metadata:
      name: bookinfo-wss
      namespace: bookinfo
      annotations:
        tsb.tetrate.io/organization: capitalone
        tsb.tetrate.io/tenant: bookinfo-sidecar
        tsb.tetrate.io/workspace: bookinfo-ws
    spec:
      failoverSettings:
        topologyChoice: CLUSTER
      defaultEastWestGatewaySettings:
        - workloadSelector:
            namespace: bookinfo
            labels:
              app: eastwest-gateway

