---
apiVersion: v1
kind: List
items:
  - apiVersion: install.tetrate.io/v1alpha1
    kind: Gateway
    metadata:
      name: bookinfo-ugw
      namespace: bookinfo
      annotations:
        tsb.tetrate.io/organization: capitalone
        tsb.tetrate.io/tenant: bookinfo-sidecar
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-gg
    spec:
      type: UNIFIED
      targetCluster: azure-centralus
      targetNamespace: bookinfo
      #eastWestOnly: true
      kubeSpec:
        service:
          type: LoadBalancer
          #annotations:
          #  external-dns.alpha.kubernetes.io/hostname: gateway.tetrate.io
  - apiVersion: install.tetrate.io/v1alpha1
    kind: Gateway
    metadata:
      name: eastwest-gateway
      namespace: eastwest
    spec:
      type: EASTWEST